server:
  port: 9093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamification
    username: postgres
    password: amir12345
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: dev
app-metadata:
  environment: development

---
spring:
  config:
    activate:
      on-profile: prod
app-metadata:
  environment: production